### ISSUE TITLE
[BUG] Binance Trading Pair Fetcher is broken

### ISSUE THREAD

**Issue by Hashira-Lars** [CoinAlpha/hummingbot#1232]
**Describe the bug**
// XEMM strategy sets some parameters to none/blank
   `Issue is present when paper-trade is enabled before creating new XEMM strategy`

**Steps To Reproduce**
Create a strategy choose Cross Exchange Market Making , Finish initial configuration.Enter `list configs`

Here are the steps to reproduce the issue (see attachments in the section below):
1.Create New Instance
2.Enter new instance
3.Before Executing config enable paper-trade
4.Enter Config ,Create new Strategy use 1 cex and 1 dex exchange(e.g: binance , bamboo-relay)
5.Finish initial Configuration 
6.Enter list configs
6.Result:none bug

**Screenshots**

![image](https://user-images.githubusercontent.com/55869559/71306588-3defd200-241d-11ea-96cf-4d75660d3020.png)

![image](https://user-images.githubusercontent.com/55869559/71306593-4a742a80-241d-11ea-9af5-31a59630fc71.png)

**Release version**
// 0.21.0

**Attachments**

[config_file.txt](https://github.com/CoinAlpha/hummingbot/files/3991263/config_file.txt)

            "branch": "development",
            "commit": "5a94dbb9d8876dd0ab2f5d166dd90193e0a25e72",
            "date": "2019-12-21T00:32:40Z",

Also tested in Previous version `0.20.0` and there was no issue like this

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Lars l Support
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by PtrckM** [comment]
Bug occurs when trading pair input as small strings as shown on screenshots below:

![image](https://user-images.githubusercontent.com/54516858/71318787-769cb380-24d0-11ea-8ffa-81dd10f4b499.png)
![image](https://user-images.githubusercontent.com/54516858/71318790-7c929480-24d0-11ea-8679-b93d85b77f75.png)
![image](https://user-images.githubusercontent.com/54516858/71318793-83b9a280-24d0-11ea-8e13-4c4babc7f0cd.png)
![image](https://user-images.githubusercontent.com/54516858/71318794-89af8380-24d0-11ea-9951-a5d3ebf35476.png)

![image](https://user-images.githubusercontent.com/54516858/71318859-6fc27080-24d1-11ea-8871-a6e630f9b339.png)

Note: taker did not check if its valid token pair and there is no show options as well on taker trading pair unlike on maker.

**Comment by znerol19619** [comment]
I just noticed that some the parameters of the xemm strategy i created 2 days ago (last friday) is set to ``none`` aswell. Both my taker and maker pair are uppercase letters.

**version**
```
Branch: development
Commit: ac91e82310f2f9d4fac0281443c0e25e45584baa
```
![ddex-bittrex-xemm-none](https://user-images.githubusercontent.com/27669951/71322715-9bf7e480-2505-11ea-8dc3-ff012bf74b68.png)


Then I tried setting up another xemm strategy again in the latest development release and still got the same results, most of the parameters are still set to ``none``. Both my taker and maker pair are uppercase letters.

**version**
```
Branch: development
Commit: 5a94dbb9d8876dd0ab2f5d166dd90193e0a25e72
```
![coinbasepro-binance-xemm-none](https://user-images.githubusercontent.com/27669951/71322864-81266f80-2507-11ea-8ee2-89d49db38965.png)

**Comment by MishaelTereso** [comment]
Paper Trade: ON
Trading Pair: ZRX/ETH (maker) & ZRX/WETH (taker) = All Uppercase
Strategy Parameters: **All Good**
Order Created

![image](https://user-images.githubusercontent.com/56957119/71349602-5fca8f80-25aa-11ea-9d51-c1522b0a2512.png)

Paper Trade: ON
Trading Pair: zrx/eth (maker) & ZRX/WETH (taker) = maker_trading_pair is lowercase 
Strategy Parameters: **All Good**
Order Created

![image](https://user-images.githubusercontent.com/56957119/71350114-889f5480-25ab-11ea-8642-a736eb1db4b6.png)


So far I am not getting any parameters sets to blank/NONE

NOTE: I used the latest release version 0.20.0 via docker and will try to perform the test thru dev branch via cloud.

**Comment by BUDDHA-TONY** [comment]
Thanks for taking your time testing , but the issue does not exist on the master branch latest. It's in my description that i tested it on `0.20.0` @MishaelTereso

**Comment by veecos2** [comment]
The issue is due to Binance Trading pair fetcher not working. So this also occurs across other strategies where market is binance. Investigating further.

**Comment by BUDDHA-TONY** [comment]
Issue with binance lower case zrx-eth pair is [RESOLVED]

![image](https://user-images.githubusercontent.com/55869559/71391022-78d05080-263d-11ea-9dc1-9e4e98a63bc5.png)

however with xemm strategy none/blank parameters still exists.tested this on the most latest dev image.Now even if you create a new strategy with paper-trade disabled it produce the none values. to resolve the issue i found a workaround which is to re-enter the api keys resulting to reverting the none values to default values.

![image](https://user-images.githubusercontent.com/55869559/71391192-2479a080-263e-11ea-98e4-00fdb200c71e.png)
 
                "branch": "development",
                "commit": "86b356f45f2eb55c3e5cc174384a3e4e1c5a8c0f",
                "date": "2019-12-24T00:50:13Z",

**Comment by veecos2** [comment]
I don't have any issues with None configs. @PtrckM @dennisocana : Can you guys replicate this and close (or) raise accordingly.

**Comment by BUDDHA-TONY** [comment]
1.Create New Instance
2.Enter new instance
3.Before Executing config enable paper-trade
4.Enter Config ,Create new Strategy use 1 cex and 1 dex exchange(e.g: binance , bamboo-relay)
5.Finish initial Configuration
6.Enter list configs
6.Result:none bug

![image](https://user-images.githubusercontent.com/55869559/71430866-33795500-2709-11ea-88ef-bb7eb8d6c989.png)

![image](https://user-images.githubusercontent.com/55869559/71430871-370cdc00-2709-11ea-9c3f-d3adbb7638ef.png)

![image](https://user-images.githubusercontent.com/55869559/71430876-3b38f980-2709-11ea-9bde-92ddb5129ef3.png)


                "branch": "development",
                "commit": "b41ddec4430d335ef5b1510f49c73fac6c394fdf",
                "date": "2019-12-24T23:13:31Z",

**Comment by PtrckM** [comment]
test using 3 VM's

1. new instance paper trade is on for xemm either its cex-cex or cex-dex produce `None`
2. new instance papertrade is off for xemm either cex-cex and cex-dex created 2nd config strategy 1.yml (same with 0.yml with no None bug) produce `None`

![image](https://user-images.githubusercontent.com/54516858/71431196-38d79f00-270b-11ea-9cc0-87cf9fac3554.png)
![image](https://user-images.githubusercontent.com/54516858/71431203-3c6b2600-270b-11ea-9037-b7cd28a995e0.png)

**Comment by znerol19619** [comment]
@veecos2 , base from my observation I think this ``none`` value appears when no api key is being entered for every config. 
Like what @BUDDHA-TONY have tested, it shows when paper trade is on before the configuration were it doesn't require to enter an api key.

another method to trigger ``none`` value with paper trade off
1. Create any strategy (PMM/XEMM/ARB) - as long as it will ask an api key
    **example**
       PMM - bittrex (no need to start)

2. Run ``config`` command and create XEMM strategy / it's best to choose the exchange that is already used on previous strategies were you are required to enter an api key so it won't ask for another one.
    **example**
       XEMM - ddex/bittrex 

_note* There are times were it would still ask for an api key even tho there's already an encrypted api key generated located in ``hummingbot_conf`` folder, which could be a bug aswell. But when asked for the 2nd time the ``none`` value won't appear because an api key is entered._

3. Run ``list configs``

**Comment by veecos2** [comment]
@znerol19619 : Yes, I believe that might be the issue, because it asks me for an api key whenever I create a configuration and I give it my api key. I have not had None issues whenever I do provide it with an api key. Can you confirm that is causing the issue and create a new bug ticket, so that we can track it seperately. This was originally caused with Binance fetcher broken and I have fixed that issue.

 Can you create a seperate issue for the same and close this ?

**Comment by znerol19619** [comment]
@veecos2 Tested again and the bug occurs when no api key is asked/entered for every config, one example that triggers it is when paper trade is ON before the configuration, where it doesn't require an api key. But the issue where it asks an api key even tho it's already entered on previous configurations is now fixed on this PR https://github.com/CoinAlpha/hummingbot/pull/1245

Will create a seperate issue for this.

**Comment by MishaelTereso** [comment]
Cross exchange advanced parameters automatically setting to 'None' value - NOT FIXED

Steps taken:
TEST #1
- Paper Trade Disabled
- Created 2 XEMM with the same config strategy values
- CEX+DEX (Binance/Bamboo Relay)
- Result: Conf Parameters - All good - Unable to reproduced the none bug

**NOTE: When I exited the 1st XEMM and created a new/2nd XEMM, the bot asked again for the API key (which should not be because it has been saved on the encrypted_binance_api_key) Just like what @znerol19619 commented, it must be another/separate bug**

TEST #2
- Paper Trade Enabled
- Created 2 XEMM with the same config strategy values
- CEX+DEX (Binance/Bamboo Relay)
- Result: NONE bug shows up.

![image](https://user-images.githubusercontent.com/56957119/71512588-e0063300-28d1-11ea-954a-785041976b27.png)

**Comment by Hashira-Lars** [comment]
Tested it with the latest dev image merged with PR #1245 the issue still persist.Will close this as @znerol19619 created a new github issue #1248 

![image](https://user-images.githubusercontent.com/55869559/71568653-fb588480-2b03-11ea-8a21-1b3808571ae7.png)

                "branch": "development",
                "commit": "38ceaf9995d7a37c49c4734b0c95e0e27f2a9632",
                "date": "2019-12-29T15:16:11Z"
